# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicnotices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=500, null=True)),
                ('designation', models.CharField(blank=True, max_length=500, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='PublicNoticeInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Public Notice', primary_key=True, serialize=False)),
                ('when_published', models.DateTimeField(blank=True, null=True)),
                ('where_published', models.CharField(blank=True, max_length=125, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='publicnotice',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicnoticeinstance',
            name='publicnotice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicnotices.PublicNotice'),
        ),
        migrations.AddField(
            model_name='publicnotice',
            name='advertiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicnotices.Advertiser'),
        ),
    ]
