# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicnotices', '0002_auto_20171113_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=125)),
            ],
        ),
        migrations.AlterField(
            model_name='publicnoticeinstance',
            name='where_published',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicnotices.Medium'),
        ),
    ]
