# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicnotices', '0003_auto_20171113_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicnotice',
            name='medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicnotices.Medium'),
        ),
    ]
