# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicnotices', '0005_auto_20171113_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.RemoveField(
            model_name='publicnotice',
            name='image',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.AddField(
            model_name='entry',
            name='publicnotice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicnotices.PublicNotice'),
        ),
    ]
