# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicnotices', '0006_auto_20171113_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicnoticeinstance',
            name='publicnotice',
        ),
        migrations.RemoveField(
            model_name='publicnoticeinstance',
            name='where_published',
        ),
        migrations.AddField(
            model_name='publicnotice',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicnotice',
            name='posted_by',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PublicNoticeInstance',
        ),
    ]
